const { useEffect, useMemo, useRef, useState } = React;

const C = { tealDark:'#143D35',teal:'#1A6B5A',tealLight:'#228B73',tealSoft:'#E6F5F0',amber:'#E8913A',amberSoft:'#FFF5E8',navy:'#1C2A36',cream:'#F5F2ED',white:'#fff',border:'#E6E0D8',red:'#DC2626',red2:'#B91C1C',green:'#22C55E',green2:'#16A34A' };
const K = { config:'tme:config', app:'tme:appState', history:'tme:history', clock:'tme:clock', sales:'tme:sales', tasks:'tme:tasks', schedule:'tme:schedule' };
const DAYS = ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];
const TASKS=[['clockIn','Clock In','START',1],['tempChart','Temperature Chart','START',1],['keySign','Key Sign','START',0],['takeKey','Take Key','START',1,1],['fridge','Fridge Temp','DURING',0],['expiry','Near Expiry','DURING',0],['eKey','E-Key Handover','HANDOVER',1,1],['eCash','E-Cash Handover','HANDOVER',1,1],['salesUpdate','Sales Update','HANDOVER',1],['waste','Waste Disposed','HANDOVER',0],['disp','Dispensary Clear','HANDOVER',0],['giveKey','Give Key','HANDOVER',1,1]];

const get=async(k,f)=>{ try{const v=window.storage?.get?await window.storage.get(k):localStorage.getItem(k); return v?JSON.parse(v):f;}catch{return f;} };
const set=async(k,v)=>{const s=JSON.stringify(v); window.storage?.set?await window.storage.set(k,s):localStorage.setItem(k,s);};
const fmt=t=>{if(!t)return'--';const[a,b]=t.split(':').map(Number);const ap=a>=12?'PM':'AM';const h=((a+11)%12)+1;return `${h}${b?':'+String(b).padStart(2,'0'):''}${ap}`};

function App(){
  const [loading,setLoading]=useState(true),[tab,setTab]=useState('Home'),[toast,setToast]=useState(''),[overlay,setOverlay]=useState(''),[shake,setShake]=useState(false);
  const [cfg,setCfg]=useState({name:'',shiftHours:'8',salesTarget:''});
  const [st,setSt]=useState({started:false,finished:false,actualStart:null,actualEnd:null,shiftStart:'',shiftEnd:'',staff:[],notes:'',photos:[],alarm:false,tempIn:'',tempOut:'',check:{}});
  const [history,setHistory]=useState([]),[clock,setClock]=useState([]),[sales,setSales]=useState({total:'',trn:'',footfall:'',no7:'',no7pcs:'',items:'',aura:''}),[schedule,setSchedule]=useState({}),[summary,setSummary]=useState(null),[rotaText,setRotaText]=useState(''),[nameFilter,setNameFilter]=useState('');
  const alarmHits = useRef({sixty:false,ten:false});

  useEffect(()=>{ document.body.style.margin=0; document.body.style.background=C.cream; init(); if('serviceWorker' in navigator) navigator.serviceWorker.register('sw.js'); },[]);
  useEffect(()=>{ if(!loading) Promise.all([set(K.config,cfg),set(K.app,st),set(K.history,history),set(K.clock,clock),set(K.sales,sales),set(K.schedule,schedule),set(K.tasks,st.check)]); },[cfg,st,history,clock,sales,schedule,loading]);
  useEffect(()=>{ if(!overlay) return; const i=setInterval(()=>setShake(s=>!s),170); return ()=>clearInterval(i); },[overlay]);
  useEffect(()=>{ if(!st.alarm||!st.shiftStart||st.started) return; const i=setInterval(()=>{ const [h,m]=st.shiftStart.split(':').map(Number); const d=new Date(); const s=new Date(); s.setHours(h,m||0,0,0); const mins=(s-d)/60000; if(mins<=60&&mins>50&&!alarmHits.current.sixty){alarmHits.current.sixty=true; vibr([200,80,200]); note('⏰ Shift starts in 60 min');} if(mins<=10&&mins>0&&!alarmHits.current.ten){alarmHits.current.ten=true; vibr([300,80,300]); note('🚨 Shift starts in 10 min');}},30000); return ()=>clearInterval(i); },[st.alarm,st.shiftStart,st.started]);

  const init=async()=>{ setCfg(await get(K.config,cfg)); const a=await get(K.app,st); setSt(a); setHistory(await get(K.history,[])); setClock(await get(K.clock,[])); setSales(await get(K.sales,sales)); const sc=await get(K.schedule,{}); setSchedule(sc); setNameFilter((await get(K.config,cfg)).name||''); setLoading(false); };
  const note=m=>{ setToast(m); setTimeout(()=>setToast(''),2200); };
  const vibr=p=>navigator.vibrate&&navigator.vibrate(p||[60]);
  const p=(x)=>setSt(s=>({...s,...x}));
  const today = DAYS[(new Date().getDay()+6)%7];
  const greeting = new Date().getHours()<12?'Good morning 👋':new Date().getHours()<17?'Good afternoon 👋':'Good evening 👋';
  const todaysShift=schedule[today] || (st.shiftStart&&st.shiftEnd?{start:st.shiftStart,end:st.shiftEnd}:null);

  const prog = useMemo(()=>{ const done=TASKS.filter(([id])=>st.check[id]||(id==='tempChart'&&st.tempIn&&st.tempOut)).length; return {done,total:TASKS.length,pct:Math.round(done*100/TASKS.length)}; },[st]);
  const reqDone = TASKS.filter(t=>t[3]).every(([id])=>st.check[id]||(id==='tempChart'&&st.tempIn&&st.tempOut));
  const ready = st.started && st.staff.length && reqDone && st.photos.length;
  const card={background:C.white,border:`1px solid ${C.border}`,borderRadius:20,padding:14,boxShadow:'0 8px 22px rgba(28,42,54,.08)',marginBottom:12};
  const inp={width:'100%',padding:'12px 10px',border:'1px solid #F0EBE3',borderRadius:12,fontFamily:'JetBrains Mono',fontSize:16};

  const toggleTask=(id)=>{ if(id==='takeKey')return setOverlay('take'); if(id==='giveKey')return setOverlay('give'); p({check:{...st.check,[id]:!st.check[id]}}); vibr([35]); };
  const keyDone=(t)=>{const id=t==='take'?'takeKey':'giveKey'; p({check:{...st.check,[id]:true}}); setOverlay(''); note(t==='take'?'Key collected':'Key returned'); vibr([90,50,90]); };
  const startShift=()=>{ p({started:true,finished:false,actualStart:Date.now(),check:{...st.check,clockIn:true}}); setOverlay('take'); note('Shift started'); vibr([120,80,120]); };
  const finishShift=()=>{ const now=Date.now(); const rec={id:now,date:new Date().toLocaleDateString(),progress:prog,state:{...st,actualEnd:now}}; setHistory(h=>[rec,...h]); setClock(c=>[{date:rec.date,in:st.actualStart,out:now,dur:((now-st.actualStart)/3600000).toFixed(2)+'h'},...c]); p({started:false,finished:true,actualEnd:now}); setSummary(rec); setTab('Summary'); note('Shift complete'); vibr([180,100,180]); };
  const addStaff=v=>{v=v.trim(); if(v&&!st.staff.includes(v)) p({staff:[...st.staff,v]});};
  const uploadPhotos=e=>Promise.all([...(e.target.files||[])].map(f=>new Promise(r=>{const fr=new FileReader(); fr.onload=()=>r(fr.result); fr.readAsDataURL(f);}))).then(imgs=>p({photos:[...st.photos,...imgs]}));

  const parseRota=t=>{ const out={...schedule}; (t||'').split('\n').map(x=>x.trim()).forEach(l=>{ if((nameFilter||cfg.name) && !l.toLowerCase().includes((nameFilter||cfg.name).toLowerCase())) return; const day=DAYS.find(d=>l.toLowerCase().includes(d.slice(0,3).toLowerCase())); const m=l.match(/(\d{1,2}:\d{2})\s*[-–]\s*(\d{1,2}:\d{2})/); if(day&&m) out[day]={start:m[1],end:m[2]}; }); setSchedule(out); if(out[today]) p({shiftStart:out[today].start,shiftEnd:out[today].end}); note('Rota applied'); };
  const runOCR=async(file)=>{ if(!file) return; note('Running OCR...'); if(!window.Tesseract){ await new Promise((res,rej)=>{const s=document.createElement('script'); s.src='https://unpkg.com/tesseract.js@5/dist/tesseract.min.js'; s.onload=res; s.onerror=rej; document.body.appendChild(s);}); } const {data}=await window.Tesseract.recognize(file,'eng'); setRotaText(data.text||''); parseRota(data.text||''); };

  const S=(k)=>Number(sales[k]||0), kd=v=>(v/11.9).toFixed(2);
  const KPI={atv:S('trn')?S('total')/S('trn'):0, ipc:S('trn')?S('items')/S('trn'):0, conv:S('footfall')?S('trn')/S('footfall')*100:0, no7:S('total')?S('no7')/S('total')*100:0, aura:S('trn')?S('aura')/S('trn')*100:0, tKd:S('total')/11.9};

  if(loading) return <div style={{minHeight:'100vh',display:'grid',placeItems:'center',fontFamily:'DM Sans',color:C.navy}}>⏳ Tracker Made Easy</div>;

  const Home=()=> <>
    <div style={{display:'flex',justifyContent:'space-between'}}><div><div style={{fontWeight:700,opacity:.75}}>{greeting}</div><div style={{fontFamily:'Playfair Display',fontWeight:800,fontSize:38,color:C.navy}}>Let’s track your <span style={{color:C.amber}}>Shift</span></div></div><div style={{...card,padding:'8px 12px'}}><div>💊 <span style={{fontFamily:'Playfair Display',color:C.teal,fontWeight:800}}>Tracker</span></div><div style={{fontSize:10,opacity:.6}}>by Vysakh</div></div></div>
    {todaysShift && <div style={{...card,color:'#fff',background:st.finished?'linear-gradient(120deg,#6b7280,#9ca3af)':st.started?`linear-gradient(120deg,${C.green},${C.green2})`:`linear-gradient(120deg,${C.tealDark},${C.teal})`}}><b>TODAY'S SHIFT</b><div style={{fontFamily:'JetBrains Mono',fontSize:32,fontWeight:800}}>{fmt(todaysShift.start)} <span style={{fontSize:18}}>to</span> {fmt(todaysShift.end)}</div>{st.started && <div>⚪ Live</div>}<div style={{fontSize:12}}>{st.staff.join(', ')}</div></div>}
    <div style={{display:'grid',gridTemplateColumns:'1fr 56px',gap:8}}><button onClick={st.started?()=>setTab('Summary'):startShift} style={{height:56,border:0,borderRadius:16,background:st.started?C.green:C.teal,color:'#fff',fontWeight:800}}>{st.started?'ON SHIFT':'▶ START SHIFT'}</button><button onClick={()=>p({alarm:!st.alarm})} style={{height:56,border:0,borderRadius:16,background:st.alarm?C.navy:'#d1d5db'}}>{st.alarm?'🔔':'🔕'}</button></div>
    {st.started && TASKS.filter(t=>t[4]&&!st.check[t[0]]).map(([id,n])=><div key={id} onClick={()=>toggleTask(id)} style={{...card,display:'flex',justifyContent:'space-between',borderLeft:`6px solid ${id==='takeKey'?C.red:id==='giveKey'?C.amber:C.teal}`}}><b style={{fontFamily:'Playfair Display',fontSize:20}}>{n.toUpperCase()}</b><span>◯</span></div>)}
    <div style={{...card,display:'flex',gap:12,alignItems:'center',background:'linear-gradient(160deg,#effcf6,#def7ec)'}}><svg width="56" height="56"><circle cx="28" cy="28" r="22" stroke="#d1fae5" strokeWidth="6" fill="none"/><circle cx="28" cy="28" r="22" stroke={C.teal} strokeWidth="6" fill="none" strokeDasharray="138" strokeDashoffset={138-(138*prog.pct/100)} transform="rotate(-90 28 28)"/><text x="28" y="33" textAnchor="middle" fontSize="12" fontFamily="JetBrains Mono">{prog.pct}%</text></svg><div><b style={{color:C.teal}}>Checklist Progress</b><div>{prog.done} of {prog.total} tasks</div></div></div>
    <div style={{...card,background:'linear-gradient(120deg,#1A3D35,#1A6B5A)',color:'#fff'}}><div style={{display:'grid',gridTemplateColumns:'repeat(7,1fr)',gap:6}}>{DAYS.map((d,i)=>{const dt=new Date();dt.setDate(new Date().getDate()-((new Date().getDay()+6)%7)+i);const sh=schedule[d];return <div key={d} onClick={()=>sh&&p({shiftStart:sh.start,shiftEnd:sh.end})} style={{padding:6,borderRadius:10,background:d===today?C.amber:sh?'rgba(255,255,255,.2)':'transparent'}}><div style={{fontSize:9}}>{d.slice(0,3).toUpperCase()}</div><div style={{fontFamily:'JetBrains Mono',fontSize:16}}>{dt.getDate()}</div><div style={{fontSize:9}}>{sh?`${fmt(sh.start)} ${fmt(sh.end)}`:'-'}</div></div>})}</div></div>
    <div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><div style={card}><div style={{fontSize:11}}>SHIFT START</div><input type="time" value={st.shiftStart} onChange={e=>p({shiftStart:e.target.value})} style={inp}/></div><div style={card}><div style={{fontSize:11}}>SHIFT END</div><input type="time" value={st.shiftEnd} onChange={e=>p({shiftEnd:e.target.value})} style={inp}/></div></div>
    <div style={card}><b style={{color:C.teal}}>Staff</b><input style={inp} placeholder="Add staff" onKeyDown={e=>{if(e.key==='Enter'){addStaff(e.target.value); e.target.value='';}}}/><div style={{marginTop:8,display:'flex',gap:6,flexWrap:'wrap'}}>{st.staff.map(s=><span key={s} style={{padding:'4px 9px',borderRadius:999,background:C.tealSoft,color:C.teal}}>{s} <b onClick={()=>p({staff:st.staff.filter(x=>x!==s)})}>×</b></span>)}</div></div>
    <div style={{...card,background:C.amberSoft}}><b>⚡ Notes</b><textarea value={st.notes} onChange={e=>p({notes:e.target.value})} placeholder="Special tasks and reminders" style={{...inp,minHeight:90,fontFamily:'DM Sans'}}/></div>
    <div style={card}><b style={{color:C.teal}}>CHECKLIST ● {prog.done}/{prog.total}</b>{['START','DURING','HANDOVER'].map(g=><div key={g}><div style={{fontWeight:800,margin:'8px 0 4px'}}>{g}</div>{TASKS.filter(t=>t[2]===g).map(([id,n,,req,big])=><div key={id} onClick={()=>toggleTask(id)} style={{display:'flex',alignItems:'center',gap:8,padding:10,borderRadius:12,marginBottom:6,background:st.check[id]?C.tealSoft:'#fff',border:`1px solid ${req&&!st.check[id]?C.amber:'#F0EBE3'}`}}><div>{st.check[id]?'✅':'◯'}</div><div style={{flex:1,fontFamily:big&&!st.check[id]?'Playfair Display':'DM Sans',textDecoration:st.check[id]?'line-through':'none'}}>{n}</div>{id==='tempChart'&&<><input value={st.tempIn} onChange={e=>p({tempIn:e.target.value,check:{...st.check,tempChart:!!e.target.value&&!!st.tempOut}})} placeholder="In" style={{...inp,width:55,padding:6}}/><input value={st.tempOut} onChange={e=>p({tempOut:e.target.value,check:{...st.check,tempChart:!!st.tempIn&&!!e.target.value}})} placeholder="Out" style={{...inp,width:55,padding:6}}/></>}{req&&<div style={{color:C.amber}}>●</div>}</div>)}</div>)}</div>
    <div style={card}><label style={{display:'block',padding:16,border:'2px dashed #94a3b8',borderRadius:12,textAlign:'center',borderColor:st.photos.length?C.teal:'#94a3b8'}}>📷 Upload Proof<input type="file" multiple accept="image/*" onChange={uploadPhotos} style={{display:'block',marginTop:8}}/></label><div style={{display:'flex',gap:6,marginTop:8,flexWrap:'wrap'}}>{st.photos.map((ph,i)=><div key={i} style={{position:'relative'}}><img src={ph} style={{width:60,height:60,objectFit:'cover',borderRadius:8}}/><button onClick={()=>p({photos:st.photos.filter((_,x)=>x!==i)})} style={{position:'absolute',top:-4,right:-4,border:0,borderRadius:'50%',background:'#ef4444',color:'#fff'}}>×</button></div>)}</div></div>
    <div style={card}>{[['Shift started',st.started],['Staff names entered',st.staff.length],['Required tasks completed',reqDone],['Proof photo uploaded',st.photos.length]].map(([t,ok])=><div key={t} style={{padding:'4px 0',color:ok?C.teal:C.navy}}>{ok?'✅':'◯'} {t}</div>)}</div>
    {st.started && !st.check.giveKey && <button onClick={()=>setOverlay('give')} style={{width:'100%',padding:16,border:0,borderRadius:16,color:'#fff',fontFamily:'Playfair Display',fontSize:28,fontWeight:900,background:`linear-gradient(135deg,${C.amber},#C47520)`,transform:`translateX(${shake?2:-2}px)`}}>GIVE KEY!!!</button>}
    <button disabled={!ready} onClick={finishShift} style={{width:'100%',marginTop:8,height:54,border:0,borderRadius:16,background:ready?C.navy:'#9ca3af',color:'#fff',fontWeight:800}}>FINISH SHIFT</button>
  </>;

  const Sales=()=> <><div style={card}><h2>Sales Entry</h2><div>KPIs AED to KD divided by 11.9</div></div>{[['total','Total Sales','AED'],['trn','Transactions','TRN'],['footfall','Footfall SFA','🦶'],['no7','No7 Amount','AED'],['no7pcs','No7 Focus Products','pcs'],['items','Total Products Sold','items'],['aura','AURA Signups','🔗']].map(([k,l,s])=><div key={k} style={{...card,background:k.includes('no7')?C.amberSoft:C.white}}><div>{l}</div><input value={sales[k]} onChange={e=>setSales({...sales,[k]:e.target.value})} style={{...inp,fontSize:18,fontWeight:800}}/><div style={{fontFamily:'JetBrains Mono'}}>{s==='AED'?`KD ${kd(S(k))}`:s}</div></div>)}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><div style={card}><b>ATV</b><div style={{fontFamily:'JetBrains Mono',fontSize:24,fontWeight:800}}>{KPI.atv.toFixed(2)} <span style={{fontWeight:400,fontSize:12}}>AED</span></div><div>{(KPI.atv/11.9).toFixed(2)} KD</div></div><div style={card}><b>IPC</b> {KPI.ipc.toFixed(2)}</div><div style={card}><b>CONV</b> <span style={{color:C.amber}}>{KPI.conv.toFixed(1)}%</span></div><div style={card}><b>No7</b> {KPI.no7.toFixed(1)}%</div><div style={card}><b>AURA</b> {KPI.aura.toFixed(1)}%</div><div style={card}><b>TOTAL KD</b> {KPI.tKd.toFixed(2)} KD</div></div></>;

  const Rota=()=> <><div style={card}><h2>Rota OCR</h2><input value={nameFilter} onChange={e=>setNameFilter(e.target.value)} placeholder="Name filter" style={inp}/><input type="file" accept="image/*" onChange={e=>runOCR(e.target.files[0])} style={{marginTop:8}}/><textarea value={rotaText} onChange={e=>setRotaText(e.target.value)} style={{...inp,minHeight:130,marginTop:8}}/><button onClick={()=>parseRota(rotaText)} style={{marginTop:8,padding:10,border:0,borderRadius:12,background:C.teal,color:'#fff'}}>Apply to Calendar</button></div><div style={card}>{DAYS.map(d=><div key={d}>{d}: {schedule[d]?`${schedule[d].start}-${schedule[d].end}`:'-'}</div>)}</div></>;
  const History=()=> <>{history.map(h=><div key={h.id} onClick={()=>{setSummary(h);setTab('Summary')}} style={card}><b>{h.date}</b><div>{h.progress.done}/{h.progress.total} tasks</div><div>{(h.state.staff||[]).join(', ')}</div></div>)}</>;
  const Settings=()=>{ const totalH=clock.reduce((a,c)=>a+((c.out-c.in)/3600000),0); return <><div style={{...card,textAlign:'center',fontFamily:'Playfair Display',fontWeight:800,fontSize:24,color:C.teal}}>Tracker Made Easy by Vysakh</div><div style={card}>{['name','shiftHours','salesTarget'].map(k=><input key={k} value={cfg[k]} onChange={e=>setCfg({...cfg,[k]:e.target.value})} placeholder={k} style={{...inp,marginBottom:8}}/>)}</div><div style={card}><div>Total shifts: {clock.length}</div><div>Total hours: {totalH.toFixed(1)}</div>{clock.map((c,i)=><div key={i} style={{fontSize:12}}>{c.date} {new Date(c.in).toLocaleTimeString()} - {new Date(c.out).toLocaleTimeString()} ({c.dur})</div>)}</div><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:8}}><button onClick={()=>{const b=new Blob([JSON.stringify({cfg,st,history,clock,sales,schedule},null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='tracker-data.json';a.click();}} style={{...card,border:0,padding:10,marginBottom:0,background:C.teal,color:'#fff'}}>Export</button><button onClick={()=>{if(confirm('Reset all data?')){Object.values(K).forEach(k=>localStorage.removeItem(k));location.reload();}}} style={{...card,border:0,padding:10,marginBottom:0,background:'#ef4444',color:'#fff'}}>Reset</button></div></> };
  const Summary=()=>{ const s=summary?.state||st; const txt=`Shift Complete\n${summary?.date||new Date().toLocaleDateString()}\nScheduled: ${fmt(s.shiftStart)}-${fmt(s.shiftEnd)}\nStaff: ${s.staff.join(', ')}`; return <><div style={{...card,background:`linear-gradient(130deg,${C.teal},${C.tealLight})`,color:'#fff'}}><div style={{fontSize:44}}>✅</div><div style={{fontFamily:'Playfair Display',fontSize:30,fontWeight:800}}>Shift Complete!</div><div>{summary?.date||new Date().toLocaleDateString()}</div></div><div style={card}>Scheduled {fmt(s.shiftStart)} to {fmt(s.shiftEnd)}<div>Actual {s.actualStart?new Date(s.actualStart).toLocaleTimeString():'-'} to {s.actualEnd?new Date(s.actualEnd).toLocaleTimeString():'-'}</div></div><div style={card}>Staff: {s.staff.join(', ')}</div><div style={card}>{TASKS.map(([id,n])=><div key={id}>{s.check[id]?'✅':'◯'} {n}</div>)}</div>{s.notes&&<div style={card}>{s.notes}</div>}<div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:8}}><button onClick={async()=>navigator.share?await navigator.share({text:txt}):(await navigator.clipboard.writeText(txt),note('Copied summary'))} style={{...card,border:0,padding:10,marginBottom:0}}>Share</button><button onClick={()=>{p({started:false,finished:false,actualStart:null,actualEnd:null,staff:[],notes:'',photos:[],alarm:false,tempIn:'',tempOut:'',check:{}}); setTab('Home');}} style={{...card,border:0,padding:10,marginBottom:0}}>New Shift</button><button onClick={()=>setTab('History')} style={{...card,border:0,padding:10,marginBottom:0}}>History</button></div></> };

  return <div style={{maxWidth:480,margin:'0 auto',padding:`max(env(safe-area-inset-top),14px) 12px calc(88px + env(safe-area-inset-bottom))`,minHeight:'100vh',background:C.cream,color:C.navy,fontFamily:'DM Sans'}}>
    {tab==='Home'&&<Home/>}{tab==='Sales'&&<Sales/>}{tab==='Rota'&&<Rota/>}{tab==='History'&&<History/>}{tab==='Settings'&&<Settings/>}{tab==='Summary'&&<Summary/>}
    <div style={{position:'fixed',left:'50%',transform:'translateX(-50%)',bottom:0,width:'min(480px,100%)',padding:'8px 8px calc(8px + env(safe-area-inset-bottom))',backdropFilter:'blur(12px) saturate(150%)',background:'rgba(255,255,255,.72)',borderTop:`1px solid ${C.border}`}}><div style={{display:'grid',gridTemplateColumns:'repeat(5,1fr)',gap:6}}>{['Home','Sales','Rota','History','Settings'].map(n=><button key={n} onClick={()=>setTab(n)} style={{border:0,padding:8,borderRadius:12,background:tab===n?C.tealSoft:'transparent',color:tab===n?C.teal:C.navy}}>{n}</button>)}</div></div>
    {toast&&<div style={{position:'fixed',bottom:100,left:'50%',transform:'translateX(-50%)',background:C.navy,color:'#fff',padding:'10px 14px',borderRadius:999}}>{toast}</div>}
    {overlay&&<div style={{position:'fixed',inset:0,background:'rgba(0,0,0,.6)',display:'grid',placeItems:'center',padding:20,zIndex:20}}><div style={{width:'100%',maxWidth:360,padding:18,borderRadius:20,color:'#fff',textAlign:'center',background:overlay==='take'?`linear-gradient(135deg,${C.red},${C.red2})`:`linear-gradient(135deg,${C.amber},#C47520)`}}><div style={{fontSize:60}}>🔑</div><div style={{fontFamily:'Playfair Display',fontWeight:900,fontSize:36,transform:`translateX(${shake?3:-3}px)`}}>{overlay==='take'?'TAKE THE KEY!!!':'GIVE KEY!!!'}</div><div style={{marginBottom:10}}>{overlay==='take'?'Collect the pharmacy key NOW':'Return the key to handover'}</div><button onClick={()=>keyDone(overlay)} style={{padding:'10px 14px',border:0,borderRadius:12}}>{overlay==='take'?'KEY TAKEN':'KEY GIVEN'}</button><div onClick={()=>setOverlay('')} style={{marginTop:8,textDecoration:'underline'}}>dismiss</div></div></div>}
  </div>;
}

ReactDOM.createRoot(document.getElementById('root')).render(<App />);
